//void nouvelEmprunt(Lecteur l, Ouvrage o);
void nouvelEmprunt(int numeroLecteur, Lecteur **tabl, int nbL, char cote[],Ouvrage **tabO, int nbo);
void retourEmprunt(int numeroLecteur, Lecteur **tabl, int nbL, char cote[],Ouvrage **tabO, int nbo);
Emprunt EmpruntVide(void);
Emprunt insererEnTeteEmprunt(Emprunt m, char cote[]);
Emprunt insererEmprunt(Emprunt m, char cote[]);
Emprunt insererEnTeteEmpruntBin(Emprunt m, char cote[], Date date);
Emprunt supprimerEnTeteEmprunt(Emprunt m);
Emprunt supprimerEmprunt(Emprunt m, char cote[]);
int longueurEmprunt(Emprunt m);
void afficherEmprunt(Emprunt m);
