Lecteur saisirLecteur(void);
void afficheLecteur(Lecteur l);
void trierEchange(Lecteur* tab[], int nb);
void echangerEchange(Lecteur* tab[], int i, int j);
int rechercheEchange(Lecteur* tab[], int nb);
int comparerNomPrenom(char* nom, char* prenom, char* nom1, char* prenom1);
void DecalerADroite(Lecteur* tab[], int n, int i);
void DecalerAGauche(Lecteur* tab[], int n, int i);
Lecteur** ajouterLecteur(Lecteur* tabL[], int* nbL, Lecteur l);
Lecteur** supprimerLecteur(Lecteur* tabL[], int* nbL, int i);
int rechercheDichoLecteur(int numeroLecteur, Lecteur **tabl, int nb);
